## Groupby() and  Aggregate, filter, transform, apply

# GroupBy: Split, Apply, Combine


Groupby() is used to make groups of any column in our dataset by passing the column name in groupby ().

The groupby function basically work on  these three  Split, Apply, Combine .

Split:-The split step involves breaking up and grouping a DataFrame depending on the
value of the specified key.

Apply:-The apply step involves computing some function, usually an aggregate, transfor‚Äê
mation, or filtering, within the individual groups.

Combine:-The combine step merges the results of these operations into an output array.

In [1]:
# reading the csv file
import pandas as pd
ipl=pd.read_csv('IPL2023_Batsman.csv',encoding='windows-1252')
ipl.head()

,match_no,Batsman,team,Run,Ball,4s,6s,out_by
0,1,Devon Conway,Chennai Super Kings,1,6,0,0,Mohammed Shami
1,1,Ruturaj Gaikwad,Chennai Super Kings,92,50,4,9,Alzarri Joseph
2,1,Moeen Ali,Chennai Super Kings,23,17,4,1,Rashid Khan
3,1,Ben Stokes,Chennai Super Kings,7,6,1,0,Rashid Khan
4,1,Ambati Rayudu,Chennai Super Kings,12,12,0,1,Joshua Little

In [2]:
# renaming  the columns name 
ipl.rename(columns={'4s':'Fours',
                    '6s':'Sixes',
                   'out_by':'Wicket taken by'},inplace=True)

In [3]:
ipl.head()

,match_no,Batsman,team,Run,Ball,Fours,Sixes,Wicket taken by
0,1,Devon Conway,Chennai Super Kings,1,6,0,0,Mohammed Shami
1,1,Ruturaj Gaikwad,Chennai Super Kings,92,50,4,9,Alzarri Joseph
2,1,Moeen Ali,Chennai Super Kings,23,17,4,1,Rashid Khan
3,1,Ben Stokes,Chennai Super Kings,7,6,1,0,Rashid Khan
4,1,Ambati Rayudu,Chennai Super Kings,12,12,0,1,Joshua Little

In [4]:
# check in the column names of the dataset 
ipl.columns

Index(['match_no', 'Batsman', 'team', 'Run', 'Ball', 'Fours', 'Sixes',
       'Wicket taken by'],
      dtype='object')

In [5]:
# checking the index of data set
ipl.index

RangeIndex(start=0, stop=1114, step=1)

In [6]:
ipl.shape

(1114, 8)

In [7]:
ipl.size

8912

In [8]:
ipl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1114 entries, 0 to 1113
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   match_no         1114 non-null   int64
 1   Batsman          1114 non-null   object
 2   team             1114 non-null   object
 3   Run              1114 non-null   int64
 4   Ball             1114 non-null   int64
 5   Fours            1114 non-null   int64
 6   Sixes            1114 non-null   int64
 7   Wicket taken by  1114 non-null   object
dtypes: int64(5), object(3)
memory usage: 69.8+ KB

In [9]:
ipl.describe()

          match_no          Run         Ball        Fours        Sixes
count  1114.000000  1114.000000  1114.000000  1114.000000  1114.000000
mean     34.609515    20.733393    14.648115     1.847397     0.951526
std      20.049515    22.933746    13.582402     2.496009     1.574557
min       1.000000     0.000000     0.000000     0.000000     0.000000
25%      17.250000     3.000000     4.000000     0.000000     0.000000
50%      34.000000    12.000000    10.000000     1.000000     0.000000
75%      52.000000    30.000000    21.000000     3.000000     1.000000
max      70.000000   124.000000    66.000000    16.000000    10.000000

In [10]:
# making row index of column match_no
ipl.set_index('match_no',inplace=True)

In [11]:
ipl.head()

,Batsman,team,Run,Ball,Fours,Sixes,Wicket taken by
match_no,,,,,,,
1,Devon Conway,Chennai Super Kings,1,6,0,0,Mohammed Shami
1,Ruturaj Gaikwad,Chennai Super Kings,92,50,4,9,Alzarri Joseph
1,Moeen Ali,Chennai Super Kings,23,17,4,1,Rashid Khan
1,Ben Stokes,Chennai Super Kings,7,6,1,0,Rashid Khan
1,Ambati Rayudu,Chennai Super Kings,12,12,0,1,Joshua Little

In [12]:
# performing the grouby () to team column 
ipl.groupby('Batsman')

We can compute the most basic split-apply-combine operation with the groupby()
method of DataFrames, passing the name of the desired Batsman column:

In [13]:
ipl.groupby('Batsman')

By applying groupby function we can not see dataframe because groupby () take in object only ,if we have have to see dataframe then we must have to apply atleast one aggregate function such as sum(),max() etc.

# Column indexing 

The GroupBy object supports column indexing in the same way as
the DataFrame, and returns a modified GroupBy object. 

its modified groupby object into series group

In [14]:
# taking another column from cups dataset 
ipl.groupby('Batsman')['team']

Here we‚Äôve selected a particular Series group from the original DataFrame group by reference to its column name. 
As we know the GroupBy object, no computation is done until we call some aggregate on the object:

In [15]:
# Taking the aggregate method to perform some arthmetic operation like ,min ,sum etc.
# By performing the aggregate methods on object then only we can see grouping of the column, lets see below exaple

ipl.groupby('Batsman')['team'].max()

Batsman
Abdul Basith                   Rajasthan Royals
Abdul Samad                 Sunrisers Hyderabad
Abhinav Manohar                  Gujarat Titans
Abhishek Sharma             Sunrisers Hyderabad
Abishek Porel                    Delhi Capitals
                               ...
Wayne Parnell       Royal Challengers Bangalore
Wriddhiman Saha                  Gujarat Titans
Yash Dhull                       Delhi Capitals
Yashasvi Jaiswal               Rajasthan Royals
Yudhvir Singh              Lucknow Super Giants
Name: team, Length: 176, dtype: object

As we mentioned earlier the GroupBy object supports column indexing in the same way as the DataFrame, and returns a modified GroupBy object into series.

As we earlier mentioned above by perfoming aggregate method we can able to see grouping of data.

In [16]:
# showing the datatype
type(ipl.groupby('Batsman')['team'].max())

pandas.core.series.Series

See as the data type is in  panda series

In [17]:
# counting the  total number of team in which the batsman have  been palyed using count aggregate .
ipl.groupby('Batsman')['team'].count()

Batsman
Abdul Basith         1
Abdul Samad          8
Abhinav Manohar      6
Abhishek Sharma     11
Abishek Porel        4
                    ..
Wayne Parnell        1
Wriddhiman Saha     14
Yash Dhull           3
Yashasvi Jaiswal    14
Yudhvir Singh        2
Name: team, Length: 176, dtype: int64

In the above output  we clearly absorb that few player has been played fro one Team only like Wayne Parnell,Abdul Basith         1
etc.

In [18]:
# adding all the team using sum aggregate
ipl.groupby('Batsman')['team'].sum()

Batsman
Abdul Basith                                         Rajasthan Royals
Abdul Samad         Sunrisers HyderabadSunrisers HyderabadSunriser...
Abhinav Manohar     Gujarat TitansGujarat TitansGujarat TitansGuja...
Abhishek Sharma     Sunrisers HyderabadSunrisers HyderabadSunriser...
Abishek Porel       Delhi CapitalsDelhi CapitalsDelhi CapitalsDelh...
                                          ...
Wayne Parnell                             Royal Challengers Bangalore
Wriddhiman Saha     Gujarat TitansGujarat TitansGujarat TitansGuja...
Yash Dhull                 Delhi CapitalsDelhi CapitalsDelhi Capitals
Yashasvi Jaiswal    Rajasthan RoyalsRajasthan RoyalsRajasthan Roya...
Yudhvir Singh                Lucknow Super GiantsLucknow Super Giants
Name: team, Length: 176, dtype: object

If you compare the total nu. of teams and sum of the team we can clearly see the Wayne Parnell has played for Royal Challengers Bangalore
and Abdul Basith has played for  Rajasthan Royals only in short they both have played for only one team

In [19]:
# fetching the highest run by a batsman in the ipl series 
ipl.groupby('Batsman')['Run'].sum().sort_values(ascending=False)

Batsman
Faf du Plessis      730
Shubman Gill        680
Virat Kohli         639
Yashasvi Jaiswal    625
Ruturaj Gaikwad     581
                   ...
Riley Meredith        0
Mohit Sharma          0
Rahul Chahar          0
Tushar Deshpande      0
Mohammed Shami        0
Name: Run, Length: 176, dtype: int64

In [20]:
# fetching the highest fours by a batsman
ipl.groupby('Batsman')['Fours'].sum().sort_values(ascending=False)

Batsman
Yashasvi Jaiswal    83
David Warner        69
Shubman Gill        67
Virat Kohli         65
Faf du Plessis      60
                    ..
Nathan Ellis         0
Noor Ahmad           0
Rahul Chahar         0
Riley Meredith       0
Yudhvir Singh        0
Name: Fours, Length: 176, dtype: int64

In [21]:
# fetching the highest six by a batsman
ipl.groupby('Batsman')['Sixes'].sum().sort_values(ascending=False)

Batsman
Faf du Plessis     36
Shivam Dube        33
Glenn Maxwell      31
Rinku Singh        29
Ruturaj Gaikwad    29
                   ..
Kedar Jadhav        0
Karn Sharma         0
Karan Sharma        0
Kagiso Rabada       0
Yudhvir Singh       0
Name: Sixes, Length: 176, dtype: int64

In [22]:
# fetching the highest ball played by a batsman
ipl.groupby('Batsman')['Ball'].sum().sort_values(ascending=False)

Batsman
Faf du Plessis       475
Virat Kohli          457
Shubman Gill         446
Ruturaj Gaikwad      397
David Warner         392
                    ...
Romario Shepherd       1
Mohammed Shami         1
Mohit Sharma           1
Mustafizur Rahman      1
Abdul Basith           1
Name: Ball, Length: 176, dtype: int64

In [23]:
# seeing the highest wicket taken by which player
ipl.groupby('Batsman')['Wicket taken by'].sum().sort_values(ascending=False)

Batsman
Harry Brook          Yuzvendra ChahalRavi BishnoiArshdeep SinghNot ...
Bhuvneshwar Kumar    Yuzvendra ChahalNot OutArjun TendulkarNot OutN...
Mayank Agarwal       Yuzvendra ChahalKrunal PandyaRahul ChaharAndre...
Adil Rashid                                Yuzvendra ChahalAmit Mishra
Atharva Taide        Yudhvir SinghMohammed SirajPiyush ChawlaRavi B...
                                           ...
Ruturaj Gaikwad      Alzarri JosephRavi BishnoiNot OutSandeep Sharm...
Ravindra Jadeja      Alzarri JosephMark WoodNot OutGlenn MaxwellKul...
Vivrant Sharma                                           Akash Madhwal
Rohit Sharma         Akash DeepTushar DeshpandeMustafizur RahmanSuy...
Romario Shepherd                                           Adil Rashid
Name: Wicket taken by, Length: 176, dtype: object

In [24]:
ipl.groupby('Batsman',sort=False)['Wicket taken by'].sum()

Batsman
Devon Conway        Mohammed ShamiMark WoodJason BehrendorffYuzven...
Ruturaj Gaikwad     Alzarri JosephRavi BishnoiNot OutSandeep Sharm...
Moeen Ali           Rashid KhanRavi BishnoiAdam ZampaNot OutNot Ou...
Ben Stokes                                      Rashid KhanAvesh Khan
Ambati Rayudu       Joshua LittleNot OutNot OutYuzvendra ChahalVij...
                                          ...
Mohammed Shami                                      Bhuvneshwar Kumar
Mohit Sharma                                                  Not Out
Sanvir Singh                                      Mohit SharmaNot Out
Fazalhaq Farooqi                                              Not Out
Vivrant Sharma                                          Akash Madhwal
Name: Wicket taken by, Length: 176, dtype: object

In [25]:
# putting the data  in ipl1 variable so we have to just call varible only instead of performing groupby everytime
ipl1=ipl.groupby('Batsman')
ipl1

# Iteration over groups

The GroupBy object supports direct iteration over the groups, returning each group as a Series or DataFrame.

If we have to see the result of how groupby works vizually that is in dataframe or in series  then we have to perform iteration over the groupby() and it support directly iteration.

In [26]:
# perfroming the Iteration over groups to see the how groupby computation look like
for batsman,batsman_df in ipl1:
    print(batsman)
    print(batsman_df)

Abdul Basith
               Batsman              team  Run  Ball  Fours  Sixes  \
match_no
32        Abdul Basith  Rajasthan Royals    1     1      0      0

         Wicket taken by
match_no
32               Not Out
Abdul Samad
              Batsman                 team  Run  Ball  Fours  Sixes  \
match_no
4         Abdul Samad  Sunrisers Hyderabad   32    32      2      1
10        Abdul Samad  Sunrisers Hyderabad   21    10      1      2
25        Abdul Samad  Sunrisers Hyderabad    9    12      1      0
40        Abdul Samad  Sunrisers Hyderabad   28    21      1      2
47        Abdul Samad  Sunrisers Hyderabad   21    18      3      0
52        Abdul Samad  Sunrisers Hyderabad   17     7      0      2
58        Abdul Samad  Sunrisers Hyderabad   37    25      1      4
62        Abdul Samad  Sunrisers Hyderabad    4     3      1      0

              Wicket taken by
match_no
4                     Not Out
10                    Not Out
25                    Run Out
40             Mitchell Marsh
47        Varun Chakaravarthy
52                    Not Out
58                    Not Out
62               Mohit Sharma
Abhinav Manohar
                  Batsman            team  Run  Ball  Fours  Sixes  \
match_no
13        Abhinav Manohar  Gujarat Titans   14     8      3      0
23        Abhinav Manohar  Gujarat Titans   27    13      0      3
30        Abhinav Manohar  Gujarat Titans    3     5      0      0
35        Abhinav Manohar  Gujarat Titans   42    21      3      3
44        Abhinav Manohar  Gujarat Titans   26    33      0      1
57        Abhinav Manohar  Gujarat Titans    2     3      0      0

          Wicket taken by
match_no
13          Suyash Sharma
23             Adam Zampa
30            Amit Mishra
35         Riley Meredith
44          Khaleel Ahmed
57        Kumar Kartikeya
Abhishek Sharma
                  Batsman                 team  Run  Ball  Fours  Sixes  \
match_no
4         Abhishek Sharma  Sunrisers Hyderabad    0     3      0      0
19        Abhishek Sharma  Sunrisers Hyderabad   32    17      3      2
25        Abhishek Sharma  Sunrisers Hyderabad    1     2      0      0
29        Abhishek Sharma  Sunrisers Hyderabad   34    26      3      1
34        Abhishek Sharma  Sunrisers Hyderabad    5     5      0      0
40        Abhishek Sharma  Sunrisers Hyderabad   67    36     12      1
47        Abhishek Sharma  Sunrisers Hyderabad    9    10      1      0
52        Abhishek Sharma  Sunrisers Hyderabad   55    34      5      2
58        Abhishek Sharma  Sunrisers Hyderabad    7     5      1      0
62        Abhishek Sharma  Sunrisers Hyderabad    4     5      1      0
65        Abhishek Sharma  Sunrisers Hyderabad   11    14      2      0

              Wicket taken by
match_no
4                 Trent Boult
19              Andre Russell
25              Piyush Chawla
29            Ravindra Jadeja
34              Kuldeep Yadav
40                 Axar Patel
47             Shardul Thakur
52        Ravichandran Ashwin
58              Yudhvir Singh
62                 Yash Dayal
65          Michael Bracewell
Abishek Porel
                Batsman            team  Run  Ball  Fours  Sixes  \
match_no
7         Abishek Porel  Delhi Capitals   20    11      0      0
11        Abishek Porel  Delhi Capitals    7     9      1      0
16        Abishek Porel  Delhi Capitals    1     3      0      0
20        Abishek Porel  Delhi Capitals    5     8      0      0

            Wicket taken by
match_no
7               Rashid Khan
11         Yuzvendra Chahal
16        Jason Behrendorff
20            Harshal Patel
Adam Zampa
             Batsman              team  Run  Ball  Fours  Sixes  \
match_no
17        Adam Zampa  Rajasthan Royals    1     1      0      0
48        Adam Zampa  Rajasthan Royals    7     9      0      0
60        Adam Zampa  Rajasthan Royals    2     6      0      0

         Wicket taken by
match_no
17               Run Out
48               Run Out
60           Karn Sharma
Adil Rashid
              Batsman                 team  Run  Ball  Fours  Sixes  \
match_no
4         Adil Rashid  Sunrisers Hyderabad   18    13      1      1
10        Adil Rashid  Sunrisers Hyderabad    4     3      1      0

           Wicket taken by
match_no
4         Yuzvendra Chahal
10             Amit Mishra
Aiden Markram
                Batsman                 team  Run  Ball  Fours  Sixes  \
match_no
10        Aiden Markram  Sunrisers Hyderabad    0     1      0      0
14        Aiden Markram  Sunrisers Hyderabad   37    21      6      0
19        Aiden Markram  Sunrisers Hyderabad   50    26      2      5
25        Aiden Markram  Sunrisers Hyderabad   22    17      1      1
29        Aiden Markram  Sunrisers Hyderabad   12    12      1      0
34        Aiden Markram  Sunrisers Hyderabad    3     5      0      0
40        Aiden Markram  Sunrisers Hyderabad    8    13      0      0
47        Aiden Markram  Sunrisers Hyderabad   41    40      4      0
52        Aiden Markram  Sunrisers Hyderabad    6     5      1      0
58        Aiden Markram  Sunrisers Hyderabad   28    20      2      1
62        Aiden Markram  Sunrisers Hyderabad   10    10      1      0
65        Aiden Markram  Sunrisers Hyderabad   18    20      0      0
69        Aiden Markram  Sunrisers Hyderabad   13     7      0      1

              Wicket taken by
match_no
10              Krunal Pandya
14                    Not Out
19        Varun Chakaravarthy
25              Cameron Green
29         Maheesh Theekshana
34                 Axar Patel
40             Mitchell Marsh
47              Vaibhav Arora
52           Yuzvendra Chahal
58              Krunal Pandya
62             Mohammed Shami
65              Shahbaz Ahmed
69                    Not Out
Ajinkya Rahane
                 Batsman                 team  Run  Ball  Fours  Sixes  \
match_no
12        Ajinkya Rahane  Chennai Super Kings   61    27      7      3
17        Ajinkya Rahane  Chennai Super Kings   31    19      2      1
24        Ajinkya Rahane  Chennai Super Kings   37    20      3      2
29        Ajinkya Rahane  Chennai Super Kings    9    10      0      0
33        Ajinkya Rahane  Chennai Super Kings   71    29      6      5
37        Ajinkya Rahane  Chennai Super Kings   15    13      0      0
49        Ajinkya Rahane  Chennai Super Kings   21    17      1      1
55        Ajinkya Rahane  Chennai Super Kings   21    20      2      0
61        Ajinkya Rahane  Chennai Super Kings   16    11      1      1

              Wicket taken by
match_no
12              Piyush Chawla
17        Ravichandran Ashwin
24          Wanindu Hasaranga
29            Mayank Markande
33                    Not Out
37        Ravichandran Ashwin
49              Piyush Chawla
55                Lalit Yadav
61        Varun Chakaravarthy
Akash Deep
             Batsman                         team  Run  Ball  Fours  Sixes  \
match_no
9         Akash Deep  Royal Challengers Bangalore   17     8      2      1

              Wicket taken by
match_no
9         Varun Chakaravarthy
Akeal Hosein
               Batsman                 team  Run  Ball  Fours  Sixes  \
match_no
40        Akeal Hosein  Sunrisers Hyderabad   16    10      1      1

         Wicket taken by
match_no
40               Not Out
Alzarri Joseph
                 Batsman            team  Run  Ball  Fours  Sixes  \
match_no
23        Alzarri Joseph  Gujarat Titans    0     0      0      0
57        Alzarri Joseph  Gujarat Titans    7    12      1      0

         Wicket taken by
match_no
23               Not Out
57               Not Out
Aman Hakim Khan
                  Batsman            team  Run  Ball  Fours  Sixes  \
match_no
3         Aman Hakim Khan  Delhi Capitals    4     5      0      0
7         Aman Hakim Khan  Delhi Capitals    8     8      0      1
20        Aman Hakim Khan  Delhi Capitals   18    10      1      1
28        Aman Hakim Khan  Delhi Capitals    0     2      0      0
34        Aman Hakim Khan  Delhi Capitals    4     2      1      0
44        Aman Hakim Khan  Delhi Capitals   51    44      3      3
55        Aman Hakim Khan  Delhi Capitals    2     3      0      0
59        Aman Hakim Khan  Delhi Capitals   16    18      1      1
67        Aman Hakim Khan  Delhi Capitals    7     9      1      0

              Wicket taken by
match_no
3                  Avesh Khan
7                 Rashid Khan
20             Mohammed Siraj
28                Nitish Rana
34          Washington Sundar
44                Rashid Khan
55                    Not Out
59               Nathan Ellis
67        Matheesha Pathirana
Ambati Rayudu
                Batsman                 team  Run  Ball  Fours  Sixes  \
match_no
1         Ambati Rayudu  Chennai Super Kings   12    12      0      1
6         Ambati Rayudu  Chennai Super Kings   27    14      2      2
12        Ambati Rayudu  Chennai Super Kings   20    16      3      0
17        Ambati Rayudu  Chennai Super Kings    1     2      0      0
24        Ambati Rayudu  Chennai Super Kings   14     6      1      1
29        Ambati Rayudu  Chennai Super Kings    9     9      1      0
37        Ambati Rayudu  Chennai Super Kings    0     2      0      0
49        Ambati Rayudu  Chennai Super Kings   12    11      0      1
55        Ambati Rayudu  Chennai Super Kings   23    17      1      1
61        Ambati Rayudu  Chennai Super Kings    4     7      0      0

              Wicket taken by
match_no
1               Joshua Little
6                     Not Out
12                    Not Out
17           Yuzvendra Chahal
24          Vijaykumar Vyshak
29            Mayank Markande
37        Ravichandran Ashwin
49             Tristan Stubbs
55              Khaleel Ahmed
61               Sunil Narine
Amit Mishra
              Batsman                  team  Run  Ball  Fours  Sixes  \
match_no
43        Amit Mishra  Lucknow Super Giants   19    30      2      0

         Wicket taken by
match_no
43         Harshal Patel
Andre Russell
                Batsman                   team  Run  Ball  Fours  Sixes  \
match_no
2         Andre Russell  Kolkata Knight Riders   35    19      3      2
9         Andre Russell  Kolkata Knight Riders    0     1      0      0
13        Andre Russell  Kolkata Knight Riders    1     2      0      0
19        Andre Russell  Kolkata Knight Riders    3     6      0      0
22        Andre Russell  Kolkata Knight Riders   21    11      3      1
28        Andre Russell  Kolkata Knight Riders   38    31      1      4
33        Andre Russell  Kolkata Knight Riders    9     6      0      1
36        Andre Russell  Kolkata Knight Riders    1     2      0      0
39        Andre Russell  Kolkata Knight Riders   34    19      2      3
47        Andre Russell  Kolkata Knight Riders   24    15      1      2
53        Andre Russell  Kolkata Knight Riders   42    23      3      3
56        Andre Russell  Kolkata Knight Riders   10    10      0      1
61        Andre Russell  Kolkata Knight Riders    2     2      0      0
68        Andre Russell  Kolkata Knight Riders    7     9      0      1

              Wicket taken by
match_no
2                  Sam Curran
9                 Karn Sharma
13                Rashid Khan
19            Mayank Markande
22                    Not Out
28                    Not Out
33        Matheesha Pathirana
36             Mohammed Siraj
39             Mohammed Shami
47            Mayank Markande
53                    Run Out
56                    KM Asif
61                    Not Out
68               Ravi Bishnoi
Anmolpreet Singh
                   Batsman                 team  Run  Ball  Fours  Sixes  \
match_no
10        Anmolpreet Singh  Sunrisers Hyderabad   31    26      3      1
52        Anmolpreet Singh  Sunrisers Hyderabad   33    25      4      1
58        Anmolpreet Singh  Sunrisers Hyderabad   36    27      7      0
62        Anmolpreet Singh  Sunrisers Hyderabad    5     4      1      0

           Wicket taken by
match_no
10           Krunal Pandya
52        Yuzvendra Chahal
58             Amit Mishra
62          Mohammed Shami
Anrich Nortje
                Batsman            team  Run  Ball  Fours  Sixes  \
match_no
7         Anrich Nortje  Delhi Capitals    4     2      1      0
11        Anrich Nortje  Delhi Capitals    0     1      0      0
16        Anrich Nortje  Delhi Capitals    5     3      1      0
20        Anrich Nortje  Delhi Capitals   23    14      4      0
34        Anrich Nortje  Delhi Capitals    2     2      0      0
44        Anrich Nortje  Delhi Capitals    3     6      0      0
67        Anrich Nortje  Delhi Capitals    0     1      0      0

         Wicket taken by
match_no
7                Not Out
11        Sandeep Sharma
16        Riley Meredith
20               Not Out
34               Run Out
44               Not Out
67               Not Out
Anuj Rawat
             Batsman                         team  Run  Ball  Fours  Sixes  \
match_no
9         Anuj Rawat  Royal Challengers Bangalore    1     5      0      0
20        Anuj Rawat  Royal Challengers Bangalore   15    22      1      0
43        Anuj Rawat  Royal Challengers Bangalore    9    11      0      0
50        Anuj Rawat  Royal Challengers Bangalore    8     3      0      1
54        Anuj Rawat  Royal Challengers Bangalore    6     4      1      0
60        Anuj Rawat  Royal Challengers Bangalore   29    11      3      2
70        Anuj Rawat  Royal Challengers Bangalore   23    15      1      1

             Wicket taken by
match_no
9              Suyash Sharma
20                   Not Out
43        Krishnappa Gowtham
50                   Not Out
54         Jason Behrendorff
60                   Not Out
70                   Not Out
Anukul Roy
             Batsman                   team  Run  Ball  Fours  Sixes  \
match_no
2         Anukul Roy  Kolkata Knight Riders    4     5      1      0
28        Anukul Roy  Kolkata Knight Riders    0     1      0      0
47        Anukul Roy  Kolkata Knight Riders   13     7      2      0
56        Anukul Roy  Kolkata Knight Riders    6     6      0      0

         Wicket taken by
match_no
2         Arshdeep Singh
28         Kuldeep Yadav
47               Not Out
56               Not Out
Arjun Tendulkar
                  Batsman            team  Run  Ball  Fours  Sixes  \
match_no
35        Arjun Tendulkar  Mumbai Indians   13     9      0      1

         Wicket taken by
match_no
35          Mohit Sharma
Arshad Khan
              Batsman            team  Run  Ball  Fours  Sixes  \
match_no
5         Arshad Khan  Mumbai Indians   15     9      0      1
12        Arshad Khan  Mumbai Indians    2     4      0      0
49        Arshad Khan  Mumbai Indians    1     2      0      0

              Wicket taken by
match_no
5                     Not Out
12           Mitchell Santner
49        Matheesha Pathirana
Arshdeep Singh
                 Batsman          team  Run  Ball  Fours  Sixes  \
match_no
27        Arshdeep Singh  Punjab Kings    0     0      0      0
38        Arshdeep Singh  Punjab Kings    2     2      0      0

         Wicket taken by
match_no
27               Not Out
38               Not Out
Atharva Taide
                Batsman          team  Run  Ball  Fours  Sixes  \
match_no
21        Atharva Taide  Punjab Kings    0     3      0      0
27        Atharva Taide  Punjab Kings    4     2      1      0
31        Atharva Taide  Punjab Kings   29    17      3      1
38        Atharva Taide  Punjab Kings   66    36      8      2
41        Atharva Taide  Punjab Kings   13    17      0      0
64        Atharva Taide  Punjab Kings   55    42      5      2
66        Atharva Taide  Punjab Kings   19    12      3      1

          Wicket taken by
match_no
21          Yudhvir Singh
27         Mohammed Siraj
31          Piyush Chawla
38           Ravi Bishnoi
41        Ravindra Jadeja
64              Retd Hurt
66          Navdeep Saini
Avesh Khan
             Batsman                  team  Run  Ball  Fours  Sixes  \
match_no
15        Avesh Khan  Lucknow Super Giants    0     1      0      0

         Wicket taken by
match_no
15               Not Out
Axar Patel
             Batsman            team  Run  Ball  Fours  Sixes  \
match_no
3         Axar Patel  Delhi Capitals   16    11      1      1
7         Axar Patel  Delhi Capitals   36    22      2      0
11        Axar Patel  Delhi Capitals    2     6      0      0
16        Axar Patel  Delhi Capitals   54    25      4      5
20        Axar Patel  Delhi Capitals   21    14      3      0
28        Axar Patel  Delhi Capitals   19    22      1      0
34        Axar Patel  Delhi Capitals   34    34      4      0
40        Axar Patel  Delhi Capitals   29    14      1      2
44        Axar Patel  Delhi Capitals   27    30      2      1
50        Axar Patel  Delhi Capitals    8     3      0      1
55        Axar Patel  Delhi Capitals   21    12      2      1
59        Axar Patel  Delhi Capitals    1     2      0      0
67        Axar Patel  Delhi Capitals   15     8      1      1

              Wicket taken by
match_no
3                   Mark Wood
7              Mohammed Shami
11           Yuzvendra Chahal
16          Jason Behrendorff
20          Vijaykumar Vyshak
28                    Not Out
34          Bhuvneshwar Kumar
40                    Not Out
44               Mohit Sharma
50                    Not Out
55        Matheesha Pathirana
59               Rahul Chahar
67              Deepak Chahar
Ayush Badoni
               Batsman                  team  Run  Ball  Fours  Sixes  \
match_no
3         Ayush Badoni  Lucknow Super Giants   18     7      1      2
6         Ayush Badoni  Lucknow Super Giants   23    18      0      0
15        Ayush Badoni  Lucknow Super Giants   30    24      4      0
21        Ayush Badoni  Lucknow Super Giants    5     6      0      0
26        Ayush Badoni  Lucknow Super Giants    1     4      0      0
30        Ayush Badoni  Lucknow Super Giants    8     6      0      0
38        Ayush Badoni  Lucknow Super Giants   43    24      3      3
43        Ayush Badoni  Lucknow Super Giants    4    11      0      0
45        Ayush Badoni  Lucknow Super Giants   59    33      2      4
51        Ayush Badoni  Lucknow Super Giants   21    11      1      2

           Wicket taken by
match_no
3          Chetan Sakariya
6         Tushar Deshpande
15           Wayne Parnell
21                 Not Out
26             Trent Boult
30                 Run Out
38        Liam Livingstone
43          Josh Hazlewood
45                 Not Out
51            Mohit Sharma
Ben Stokes
             Batsman                 team  Run  Ball  Fours  Sixes  \
match_no
1         Ben Stokes  Chennai Super Kings    7     6      1      0
6         Ben Stokes  Chennai Super Kings    8     8      1      0

         Wicket taken by
match_no
1            Rashid Khan
6             Avesh Khan
Bhanuka Rajapaksa
                    Batsman          team  Run  Ball  Fours  Sixes  \
match_no
2         Bhanuka Rajapaksa  Punjab Kings   50    32      5      2
8         Bhanuka Rajapaksa  Punjab Kings    1     1      0      0
18        Bhanuka Rajapaksa  Punjab Kings   20    26      1      0
53        Bhanuka Rajapaksa  Punjab Kings    0     3      0      0

             Wicket taken by
match_no
2                Umesh Yadav
8         retd hurt(Not Out)
18            Alzarri Joseph
53              Harshit Rana
Bhuvneshwar Kumar
                    Batsman                 team  Run  Ball  Fours  Sixes  \
match_no
4         Bhuvneshwar Kumar  Sunrisers Hyderabad    6    10      0      0
10        Bhuvneshwar Kumar  Sunrisers Hyderabad    0     0      0      0
25        Bhuvneshwar Kumar  Sunrisers Hyderabad    2     5      0      0
47        Bhuvneshwar Kumar  Sunrisers Hyderabad    5     5      1      0
58        Bhuvneshwar Kumar  Sunrisers Hyderabad    2     1      0      0
62        Bhuvneshwar Kumar  Sunrisers Hyderabad   27    26      3      0

           Wicket taken by
match_no
4         Yuzvendra Chahal
10                 Not Out
25         Arjun Tendulkar
47                 Not Out

               Batsman                   team  Run  Ball  Fours  Sixes  \
match_no
13        N Jagadeesan  Kolkata Knight Riders    6     8      1      0
19        N Jagadeesan  Kolkata Knight Riders   36    21      5      1
22        N Jagadeesan  Kolkata Knight Riders    0     5      0      0
33        N Jagadeesan  Kolkata Knight Riders    1     3      0      0
36        N Jagadeesan  Kolkata Knight Riders   27    29      4      0
39        N Jagadeesan  Kolkata Knight Riders   19    15      4      0

            Wicket taken by
match_no
13            Joshua Little
19          Mayank Markande
22            Cameron Green
33         Tushar Deshpande
36        Vijaykumar Vyshak
39           Mohammed Shami
Nathan Ellis
               Batsman          team  Run  Ball  Fours  Sixes  Wicket taken by
match_no
14        Nathan Ellis  Punjab Kings    0     5      0      0  Mayank Markande
27        Nathan Ellis  Punjab Kings    1     2      0      0   Mohammed Siraj
Naveen-ul-Haq
                Batsman                  team  Run  Ball  Fours  Sixes  \
match_no
43        Naveen-ul-Haq  Lucknow Super Giants   13    13      2      0
68        Naveen-ul-Haq  Lucknow Super Giants    2     3      0      0

         Wicket taken by
match_no
43        Josh Hazlewood
68               Not Out
Nehal Wadhera
                Batsman            team  Run  Ball  Fours  Sixes  \
match_no
5         Nehal Wadhera  Mumbai Indians   21    13      1      2
22        Nehal Wadhera  Mumbai Indians    6     4      1      0
31        Nehal Wadhera  Mumbai Indians    0     1      0      0
35        Nehal Wadhera  Mumbai Indians   40    21      3      3
49        Nehal Wadhera  Mumbai Indians   64    51      8      1
54        Nehal Wadhera  Mumbai Indians   52    34      4      3
57        Nehal Wadhera  Mumbai Indians   15     7      1      1
63        Nehal Wadhera  Mumbai Indians   16    20      2      0

              Wicket taken by
match_no
5                 Karn Sharma
22            Lockie Ferguson
31             Arshdeep Singh
35               Mohit Sharma
49        Matheesha Pathirana
54                    Not Out
57                Rashid Khan
63                Mohsin Khan
Nicholas Pooran
                  Batsman                  team  Run  Ball  Fours  Sixes  \
match_no
3         Nicholas Pooran  Lucknow Super Giants   36    21      2      3
6         Nicholas Pooran  Lucknow Super Giants   32    18      2      3
10        Nicholas Pooran  Lucknow Super Giants   11     6      1      1
15        Nicholas Pooran  Lucknow Super Giants   62    19      4      7
21        Nicholas Pooran  Lucknow Super Giants    0     1      0      0
26        Nicholas Pooran  Lucknow Super Giants   29    20      2      1
30        Nicholas Pooran  Lucknow Super Giants    1     7      0      0
38        Nicholas Pooran  Lucknow Super Giants   45    19      7      1
43        Nicholas Pooran  Lucknow Super Giants    9     7      0      1
45        Nicholas Pooran  Lucknow Super Giants   20    31      0      0
51        Nicholas Pooran  Lucknow Super Giants    3     6      0      0
58        Nicholas Pooran  Lucknow Super Giants   44    13      3      4
63        Nicholas Pooran  Lucknow Super Giants    8     8      1      0
68        Nicholas Pooran  Lucknow Super Giants   58    30      4      5

              Wicket taken by
match_no
3               Khaleel Ahmed
6            Tushar Deshpande
10                    Not Out
15             Mohammed Siraj
21              Kagiso Rabada
26                    Run Out
30                 Noor Ahmad
38             Arshdeep Singh
43                Karn Sharma
45        Matheesha Pathirana
51                 Noor Ahmad
58                    Not Out
63                    Not Out
68             Shardul Thakur
Nitish Rana
              Batsman                   team  Run  Ball  Fours  Sixes  \
match_no
2         Nitish Rana  Kolkata Knight Riders   24    17      3      1
9         Nitish Rana  Kolkata Knight Riders    1     5      0      0
13        Nitish Rana  Kolkata Knight Riders   45    29      4      3
19        Nitish Rana  Kolkata Knight Riders   75    41      5      6
22        Nitish Rana  Kolkata Knight Riders    5    10      0      0
28        Nitish Rana  Kolkata Knight Riders    4     7      1      0
33        Nitish Rana  Kolkata Knight Riders   27    20      4      1
36        Nitish Rana  Kolkata Knight Riders   48    21      3      4
39        Nitish Rana  Kolkata Knight Riders    4     3      1      0
47        Nitish Rana  Kolkata Knight Riders   42    31      3      3
53        Nitish Rana  Kolkata Knight Riders   51    38      6      1
56        Nitish Rana  Kolkata Knight Riders   22    17      2      0
61        Nitish Rana  Kolkata Knight Riders   57    44      6      1
68        Nitish Rana  Kolkata Knight Riders    8    10      1      0

            Wicket taken by
match_no
2             Sikandar Raza
9         Michael Bracewell
13           Alzarri Joseph
19              T Natarajan
22          Hrithik Shokeen
28            Ishant Sharma
33          Ravindra Jadeja
36        Wanindu Hasaranga
39            Joshua Little
47            Aiden Markram
53             Rahul Chahar
56         Yuzvendra Chahal
61                  Not Out
68              Yash Thakur
Noor Ahmad
             Batsman            team  Run  Ball  Fours  Sixes  Wicket taken by
match_no
57        Noor Ahmad  Gujarat Titans    1     3      0      0  Kumar Kartikeya
62        Noor Ahmad  Gujarat Titans    0     1      0      0          Run Out
Philip Salt
              Batsman            team  Run  Ball  Fours  Sixes  \
match_no
28        Philip Salt  Delhi Capitals    5     3      1      0
34        Philip Salt  Delhi Capitals    0     1      0      0
40        Philip Salt  Delhi Capitals   59    35      9      0
44        Philip Salt  Delhi Capitals    0     1      0      0
50        Philip Salt  Delhi Capitals   87    45      8      6
55        Philip Salt  Delhi Capitals   17    11      1      2
59        Philip Salt  Delhi Capitals   21    17      3      0
64        Philip Salt  Delhi Capitals   26    14      2      2
67        Philip Salt  Delhi Capitals    3     6      0      0

            Wicket taken by
match_no
28               Anukul Roy
34        Bhuvneshwar Kumar
40          Mayank Markande
44           Mohammed Shami
50              Karn Sharma
55            Deepak Chahar
59            Harpreet Brar
64                  Not Out
67            Deepak Chahar
Piyush Chawla
                Batsman            team  Run  Ball  Fours  Sixes  \
match_no
12        Piyush Chawla  Mumbai Indians    5     6      0      0
35        Piyush Chawla  Mumbai Indians   18    12      1      1
49        Piyush Chawla  Mumbai Indians    2     2      0      0

         Wicket taken by
match_no
12               Not Out
35               Run Out
49               Not Out
Prabhsimran Singh
                    Batsman          team  Run  Ball  Fours  Sixes  \
match_no
2         Prabhsimran Singh  Punjab Kings   23    12      2      2
8         Prabhsimran Singh  Punjab Kings   60    34      7      3
14        Prabhsimran Singh  Punjab Kings    0     1      0      0
18        Prabhsimran Singh  Punjab Kings    0     2      0      0
21        Prabhsimran Singh  Punjab Kings    4     4      1      0
27        Prabhsimran Singh  Punjab Kings   46    30      3      4
31        Prabhsimran Singh  Punjab Kings   26    17      1      2
38        Prabhsimran Singh  Punjab Kings    9    13      2      0
41        Prabhsimran Singh  Punjab Kings   42    24      4      2
46        Prabhsimran Singh  Punjab Kings    9     7      1      0
53        Prabhsimran Singh  Punjab Kings   12     8      3      0
59        Prabhsimran Singh  Punjab Kings  103    65     10      6
64        Prabhsimran Singh  Punjab Kings   22    19      4      0
66        Prabhsimran Singh  Punjab Kings    2     2      0      0

            Wicket taken by
match_no
2               Tim Southee
8              Jason Holder
14        Bhuvneshwar Kumar
18           Mohammed Shami
21            Yudhvir Singh
27            Wayne Parnell
31          Arjun Tendulkar
38            Naveen-ul-Haq
41          Ravindra Jadeja
46              Arshad Khan
53             Harshit Rana
59             Mukesh Kumar
64               Axar Patel
66              Trent Boult
Praveen Dubey
                Batsman            team  Run  Ball  Fours  Sixes  \
match_no
59        Praveen Dubey  Delhi Capitals   16    20      2      0

         Wicket taken by
match_no
59          Nathan Ellis
Prerak Mankad
                Batsman                  team  Run  Ball  Fours  Sixes  \
match_no
30        Prerak Mankad  Lucknow Super Giants    0     0      0      0
58        Prerak Mankad  Lucknow Super Giants   64    45      7      2
63        Prerak Mankad  Lucknow Super Giants    0     1      0      0
68        Prerak Mankad  Lucknow Super Giants   26    20      5      0

            Wicket taken by
match_no
30                  Not Out
58                  Not Out
63        Jason Behrendorff
68            Vaibhav Arora
Prithvi Shaw
               Batsman            team  Run  Ball  Fours  Sixes  \
match_no
3         Prithvi Shaw  Delhi Capitals   12     9      2      0
7         Prithvi Shaw  Delhi Capitals    7     5      1      0
11        Prithvi Shaw  Delhi Capitals    0     3      0      0
16        Prithvi Shaw  Delhi Capitals   15    10      3      0
20        Prithvi Shaw  Delhi Capitals    0     2      0      0
28        Prithvi Shaw  Delhi Capitals   13    11      2      0
64        Prithvi Shaw  Delhi Capitals   54    38      7      1
67        Prithvi Shaw  Delhi Capitals    5     7      1      0

              Wicket taken by
match_no
3                   Mark Wood
7              Mohammed Shami
11                Trent Boult
16            Hrithik Shokeen
20                    Run Out
28        Varun Chakaravarthy
64                 Sam Curran
67           Tushar Deshpande
Priyam Garg
              Batsman            team  Run  Ball  Fours  Sixes  \
match_no
40        Priyam Garg  Delhi Capitals   12     9      1      0
44        Priyam Garg  Delhi Capitals   10    14      0      0

          Wicket taken by
match_no
40        Mayank Markande
44         Mohammed Shami
Quinton de Kock
                  Batsman                  team  Run  Ball  Fours  Sixes  \
match_no
51        Quinton de Kock  Lucknow Super Giants   70    41      7      3
58        Quinton de Kock  Lucknow Super Giants   29    19      3      1
63        Quinton de Kock  Lucknow Super Giants   16    15      0      2
68        Quinton de Kock  Lucknow Super Giants   28    27      0      2

              Wicket taken by
match_no
51                Rashid Khan
58            Mayank Markande
63              Piyush Chawla
68        Varun Chakaravarthy
Rahmanullah Gurbaz
                     Batsman                   team  Run  Ball  Fours  Sixes  \
match_no
2         Rahmanullah Gurbaz  Kolkata Knight Riders   22    16      3      1
9         Rahmanullah Gurbaz  Kolkata Knight Riders   57    44      6      3
39        Rahmanullah Gurbaz  Kolkata Knight Riders   81    39      5      7
47        Rahmanullah Gurbaz  Kolkata Knight Riders    0     1      0      0
53        Rahmanullah Gurbaz  Kolkata Knight Riders   15    12      1      1
56        Rahmanullah Gurbaz  Kolkata Knight Riders   18    12      1      2
61        Rahmanullah Gurbaz  Kolkata Knight Riders    1     4      0      0
68        Rahmanullah Gurbaz  Kolkata Knight Riders   10    15      0      0

         Wicket taken by
match_no
2           Nathan Ellis
9            Karn Sharma
39            Noor Ahmad
47          Marco Jansen
53          Nathan Ellis
56           Trent Boult
61         Deepak Chahar
68           Yash Thakur
Rahmanullah Gurbaz¬†
                      Batsman                   team  Run  Ball  Fours  Sixes  \
match_no
13        Rahmanullah Gurbaz¬†  Kolkata Knight Riders   15    12      1      1
19        Rahmanullah Gurbaz¬†  Kolkata Knight Riders    0     3      0      0
22        Rahmanullah Gurbaz¬†  Kolkata Knight Riders    8    12      0      0

            Wicket taken by
match_no
13           Mohammed Shami
19        Bhuvneshwar Kumar
22            Piyush Chawla
Rahul Chahar
               Batsman          team  Run  Ball  Fours  Sixes  Wicket taken by
match_no
14        Rahul Chahar  Punjab Kings    0     8      0      0  Mayank Markande
38        Rahul Chahar  Punjab Kings    0     1      0      0      Yash Thakur
64        Rahul Chahar  Punjab Kings    0     0      0      0          Not Out
Rahul Tewatia
                Batsman            team  Run  Ball  Fours  Sixes  \
match_no
1         Rahul Tewatia  Gujarat Titans   15    14      1      1
18        Rahul Tewatia  Gujarat Titans    5     2      1      0
23        Rahul Tewatia  Gujarat Titans    1     1      0      0
30        Rahul Tewatia  Gujarat Titans    2     2      0      0
35        Rahul Tewatia  Gujarat Titans   20     5      0      3
44        Rahul Tewatia  Gujarat Titans   20     7      0      3
57        Rahul Tewatia  Gujarat Titans   14    13      1      0
62        Rahul Tewatia  Gujarat Titans    3     3      0      0
70        Rahul Tewatia  Gujarat Titans    4     5      0      0

           Wicket taken by
match_no
1                  Not Out
18                 Not Out
23                 Not Out
30                 Not Out
35                 Not Out
44           Ishant Sharma
57           Piyush Chawla
62        Fazalhaq Farooqi
70                 Not Out
Rahul Tripathi
                 Batsman                 team  Run  Ball  Fours  Sixes  \
match_no
4         Rahul Tripathi  Sunrisers Hyderabad    0     2      0      0
10        Rahul Tripathi  Sunrisers Hyderabad   35    41      4      0
14        Rahul Tripathi  Sunrisers Hyderabad   74    48     10      3
19        Rahul Tripathi  Sunrisers Hyderabad    9     4      2      0
25        Rahul Tripathi  Sunrisers Hyderabad    7     5      1      0
29        Rahul Tripathi  Sunrisers Hyderabad   21    21      1      1
34        Rahul Tripathi  Sunrisers Hyderabad   15    21      0      0
40        Rahul Tripathi  Sunrisers Hyderabad   10     6      0      1
47        Rahul Tripathi  Sunrisers Hyderabad   20     9      3      1
52        Rahul Tripathi  Sunrisers Hyderabad   47    29      2      3
58        Rahul Tripathi  Sunrisers Hyderabad   20    13      4      0
62        Rahul Tripathi  Sunrisers Hyderabad    1     2      0      0
65        Rahul Tripathi  Sunrisers Hyderabad   15    12      2      1

            Wicket taken by
match_no
4               Trent Boult
10              Yash Thakur
14                  Not Out
19            Andre Russell
25        Jason Behrendorff
29          Ravindra Jadeja
34            Ishant Sharma
40           Mitchell Marsh
47            Andre Russell
52         Yuzvendra Chahal
58              Yash Thakur
62           Mohammed Shami
65        Michael Bracewell
Rashid Khan
              Batsman            team  Run  Ball  Fours  Sixes  \
match_no
1         Rashid Khan  Gujarat Titans   10     3      1      1
23        Rashid Khan  Gujarat Titans    1     1      0      0
35        Rashid Khan  Gujarat Titans    2     1      0      0
44        Rashid Khan  Gujarat Titans    3     2      0      0
57        Rashid Khan  Gujarat Titans   79    32      3     10
62        Rashid Khan  Gujarat Titans    0     1      0      0

            Wicket taken by
match_no
1                   Not Out
23                  Run Out
35                  Not Out
44                  Not Out
57                  Not Out
62        Bhuvneshwar Kumar
Ravi Bishnoi
               Batsman                  team  Run  Ball  Fours  Sixes  \
match_no
15        Ravi Bishnoi  Lucknow Super Giants    3     2      0      0
21        Ravi Bishnoi  Lucknow Super Giants    3     1      0      0
30        Ravi Bishnoi  Lucknow Super Giants    0     1      0      0
43        Ravi Bishnoi  Lucknow Super Giants    5    10      0      0
51        Ravi Bishnoi  Lucknow Super Giants    4     5      1      0
68        Ravi Bishnoi  Lucknow Super Giants    2     2      0      0

         Wicket taken by
match_no
15               Not Out
21               Not Out
30               Not Out
43               Run Out
51               Not Out
68        Shardul Thakur
Ravichandran Ashwin
                      Batsman              team  Run  Ball  Fours  Sixes  \
match_no
4         Ravichandran Ashwin  Rajasthan Royals    1     2      0      0
8         Ravichandran Ashwin  Rajasthan Royals    0     4      0      0
17        Ravichandran Ashwin  Rajasthan Royals   30    22      1      2
23        Ravichandran Ashwin  Rajasthan Royals   10     3      1      1
26        Ravichandran Ashwin  Rajasthan Royals    3     2      0      0
32        Ravichandran Ashwin  Rajasthan Royals   12     6      2      0
37        Ravichandran Ashwin  Rajasthan Royals    1     1      0      0
42        Ravichandran Ashwin  Rajasthan Royals    8     5      1      0
48        Ravichandran Ashwin  Rajasthan Royals    2     6      0      0
60        Ravichandran Ashwin  Rajasthan Royals    0     0      0      0

         Wicket taken by
match_no
4                Not Out
8         Arshdeep Singh
17           Akash Singh
23        Mohammed Shami
26               Not Out
32         Harshal Patel
37               Not Out
42               Not Out
48           Rashid Khan
60               Run Out
Ravindra Jadeja
                  Batsman                 team  Run  Ball  Fours  Sixes  \
match_no
1         Ravindra Jadeja  Chennai Super Kings    1     2      0      0
6         Ravindra Jadeja  Chennai Super Kings    3     6      0      0
17        Ravindra Jadeja  Chennai Super Kings   25    15      1      2
24        Ravindra Jadeja  Chennai Super Kings   10     8      0      1
33        Ravindra Jadeja  Chennai Super Kings   18     8      0      2
37        Ravindra Jadeja  Chennai Super Kings   23    15      3      0
41        Ravindra Jadeja  Chennai Super Kings   12    10      0      0
55        Ravindra Jadeja  Chennai Super Kings   21    16      1      1
61        Ravindra Jadeja  Chennai Super Kings   20    24      0      1
67        Ravindra Jadeja  Chennai Super Kings   20     7      3      1

             Wicket taken by
match_no
1             Alzarri Joseph
6                  Mark Wood
17                   Not Out
24             Glenn Maxwell
33        Kulwant Khejroliya
37                   Not Out
41                Sam Curran
55            Mitchell Marsh
61             Vaibhav Arora
67                   Not Out
Rilee Rossouw
                Batsman            team  Run  Ball  Fours  Sixes  \
match_no
3         Rilee Rossouw  Delhi Capitals   30    20      3      1
7         Rilee Rossouw  Delhi Capitals    0     1      0      0
11        Rilee Rossouw  Delhi Capitals   14    12      2      0
44        Rilee Rossouw  Delhi Capitals    8     6      2      0
50        Rilee Rossouw  Delhi Capitals   35    22      1      3
55        Rilee Rossouw  Delhi Capitals   35    37      2      1
59        Rilee Rossouw  Delhi Capitals    5     5      1      0
64        Rilee Rossouw  Delhi Capitals   82    37      6      6
67        Rilee Rossouw  Delhi Capitals    0     1      0      0

              Wicket taken by
match_no
3                  Avesh Khan
7              Alzarri Joseph
11        Ravichandran Ashwin
44             Mohammed Shami
50                    Not Out
55            Ravindra Jadeja
59              Harpreet Brar
64                    Not Out
67              Deepak Chahar
Riley Meredith
                 Batsman            team  Run  Ball  Fours  Sixes  \
match_no
35        Riley Meredith  Mumbai Indians    0     2      0      0

         Wicket taken by
match_no
35               Not Out
Rinku Singh
              Batsman                   team  Run  Ball  Fours  Sixes  \
match_no
2         Rinku Singh  Kolkata Knight Riders    4     4      0      0

As we see we have iterated our all the groupby data by iterating over it.

In [27]:
# we can acess one  specific datafamre with the help of  using get_groups() 
ipl1.get_group('Abdul Samad')

,Batsman,team,Run,Ball,Fours,Sixes,Wicket taken by
match_no,,,,,,,
4,Abdul Samad,Sunrisers Hyderabad,32,32,2,1,Not Out
10,Abdul Samad,Sunrisers Hyderabad,21,10,1,2,Not Out
25,Abdul Samad,Sunrisers Hyderabad,9,12,1,0,Run Out
40,Abdul Samad,Sunrisers Hyderabad,28,21,1,2,Mitchell Marsh
47,Abdul Samad,Sunrisers Hyderabad,21,18,3,0,Varun Chakaravarthy
52,Abdul Samad,Sunrisers Hyderabad,17,7,0,2,Not Out
58,Abdul Samad,Sunrisers Hyderabad,37,25,1,4,Not Out
62,Abdul Samad,Sunrisers Hyderabad,4,3,1,0,Mohit Sharma

In [28]:
ipl1.get_group('MS Dhoni')

,Batsman,team,Run,Ball,Fours,Sixes,Wicket taken by
match_no,,,,,,,
1,MS Dhoni,Chennai Super Kings,14,7,1,1,Not Out
6,MS Dhoni,Chennai Super Kings,12,3,0,2,Mark Wood
17,MS Dhoni,Chennai Super Kings,32,17,1,3,Not Out
24,MS Dhoni,Chennai Super Kings,1,1,0,0,Not Out
33,MS Dhoni,Chennai Super Kings,2,3,0,0,Not Out
41,MS Dhoni,Chennai Super Kings,13,4,0,2,Not Out
49,MS Dhoni,Chennai Super Kings,2,3,0,0,Not Out
55,MS Dhoni,Chennai Super Kings,20,9,1,2,Mitchell Marsh
61,MS Dhoni,Chennai Super Kings,2,3,0,0,Not Out
67,MS Dhoni,Chennai Super Kings,5,4,0,0,Not Out

In [29]:
ipl1.get_group('Devon Conway')

,Batsman,team,Run,Ball,Fours,Sixes,Wicket taken by
match_no,,,,,,,
1,Devon Conway,Chennai Super Kings,1,6,0,0,Mohammed Shami
6,Devon Conway,Chennai Super Kings,47,29,5,2,Mark Wood
12,Devon Conway,Chennai Super Kings,0,4,0,0,Jason Behrendorff
17,Devon Conway,Chennai Super Kings,50,38,6,0,Yuzvendra Chahal
24,Devon Conway,Chennai Super Kings,83,45,6,6,Harshal Patel
33,Devon Conway,Chennai Super Kings,56,40,4,3,Varun Chakaravarthy
37,Devon Conway,Chennai Super Kings,8,16,1,0,Adam Zampa
41,Devon Conway,Chennai Super Kings,92,52,16,1,Arshdeep Singh
49,Devon Conway,Chennai Super Kings,44,42,4,0,Akash Madhwal
55,Devon Conway,Chennai Super Kings,10,13,1,0,Axar Patel
61,Devon Conway,Chennai Super Kings,30,28,3,0,Shardul Thakur
67,Devon Conway,Chennai Super Kings,87,52,11,3,Anrich Nortje

In [30]:
# we can perform agrgregate method on individuals batsman by using get_group method
ipl1.get_group('Devon Conway').sum()

Batsman            Devon ConwayDevon ConwayDevon ConwayDevon Conw...
team               Chennai Super KingsChennai Super KingsChennai ...
Run                                                              508
Ball                                                             365
Fours                                                             57
Sixes                                                             15
Wicket taken by    Mohammed ShamiMark WoodJason BehrendorffYuzven...
dtype: object

In [31]:
# finding maximum best score  by Devon Conway in IPL 2023 season 
ipl1.get_group('Devon Conway').max()

Batsman                   Devon Conway
team               Chennai Super Kings
Run                                 92
Ball                                52
Fours                               16
Sixes                                6
Wicket taken by       Yuzvendra Chahal
dtype: object

In [32]:
# finding min score  by Devon Conway in IPL 2023 season 
ipl1.get_group('Devon Conway').min()

Batsman                   Devon Conway
team               Chennai Super Kings
Run                                  0
Ball                                 4
Fours                                0
Sixes                                0
Wicket taken by             Adam Zampa
dtype: object

In [33]:
# we can fetch some data of player Shikhar Dhawan 
ipl1.get_group('Shikhar Dhawan')

,Batsman,team,Run,Ball,Fours,Sixes,Wicket taken by
match_no,,,,,,,
2,Shikhar Dhawan,Punjab Kings,40,29,6,0,Varun Chakaravarthy
8,Shikhar Dhawan,Punjab Kings,86,56,9,3,Not Out
14,Shikhar Dhawan,Punjab Kings,99,66,12,5,Not Out
18,Shikhar Dhawan,Punjab Kings,8,8,2,0,Joshua Little
38,Shikhar Dhawan,Punjab Kings,1,2,0,0,Marcus Stoinis
41,Shikhar Dhawan,Punjab Kings,28,15,4,1,Tushar Deshpande
46,Shikhar Dhawan,Punjab Kings,30,20,5,0,Piyush Chawla
53,Shikhar Dhawan,Punjab Kings,57,47,9,1,Nitish Rana
59,Shikhar Dhawan,Punjab Kings,7,5,0,1,Ishant Sharma
64,Shikhar Dhawan,Punjab Kings,0,1,0,0,Ishant Sharma
66,Shikhar Dhawan,Punjab Kings,17,12,2,1,Adam Zampa

In [34]:
# we can perform individuals coulmns aggregate () also like=team ,runs etc
ipl1.get_group('Shikhar Dhawan')[['Fours','Sixes']].sum()

Fours    49
Sixes    12
dtype: int64

In [35]:
# we can calculate overall runs  fours sixes and ball 
ipl1.get_group('Shikhar Dhawan')[['Fours','Sixes','Ball','Run']].sum()

Fours     49
Sixes     12
Ball     261
Run      373
dtype: int64

In [36]:
# instead of apply one by one aggregate () we can pass list of aggregate methods 
# we will see more in detal in the aggregate heading 
ipl1.get_group('Shikhar Dhawan').aggregate(['min',  max])

,Batsman,team,Run,Ball,Fours,Sixes,Wicket taken by
min,Shikhar Dhawan,Punjab Kings,0,1,0,0,Adam Zampa
max,Shikhar Dhawan,Punjab Kings,99,66,12,5,Varun Chakaravarthy

In [37]:
# see the virat  kohli data
ipl1.get_group('Virat Kohli')

,Batsman,team,Run,Ball,Fours,Sixes,Wicket taken by
match_no,,,,,,,
5,Virat Kohli,Royal Challengers Bangalore,82,49,6,5,Not Out
9,Virat Kohli,Royal Challengers Bangalore,21,18,3,0,Sunil Narine
15,Virat Kohli,Royal Challengers Bangalore,61,44,4,4,Amit Mishra
20,Virat Kohli,Royal Challengers Bangalore,50,34,6,1,Lalit Yadav
24,Virat Kohli,Royal Challengers Bangalore,6,4,1,0,Akash Singh
27,Virat Kohli,Royal Challengers Bangalore,59,47,5,1,Harpreet Brar
32,Virat Kohli,Royal Challengers Bangalore,0,1,0,0,Trent Boult
36,Virat Kohli,Royal Challengers Bangalore,54,37,6,0,Andre Russell
43,Virat Kohli,Royal Challengers Bangalore,31,30,3,0,Ravi Bishnoi
50,Virat Kohli,Royal Challengers Bangalore,55,46,5,0,Mukesh Kumar
54,Virat Kohli,Royal Challengers Bangalore,1,4,0,0,Jason Behrendorff
60,Virat Kohli,Royal Challengers Bangalore,18,19,1,0,KM Asif
65,Virat Kohli,Royal Challengers Bangalore,100,63,12,4,Bhuvneshwar Kumar
70,Virat Kohli,Royal Challengers Bangalore,101,61,13,1,Not Out

In [38]:
ipl1.get_group('Virat Kohli')[['Run','Fours','Sixes']].sum()

Run      639
Fours     65
Sixes     16
dtype: int64

In [39]:
ipl1.get_group('Virat Kohli')

,Batsman,team,Run,Ball,Fours,Sixes,Wicket taken by
match_no,,,,,,,
5,Virat Kohli,Royal Challengers Bangalore,82,49,6,5,Not Out
9,Virat Kohli,Royal Challengers Bangalore,21,18,3,0,Sunil Narine
15,Virat Kohli,Royal Challengers Bangalore,61,44,4,4,Amit Mishra
20,Virat Kohli,Royal Challengers Bangalore,50,34,6,1,Lalit Yadav
24,Virat Kohli,Royal Challengers Bangalore,6,4,1,0,Akash Singh
27,Virat Kohli,Royal Challengers Bangalore,59,47,5,1,Harpreet Brar
32,Virat Kohli,Royal Challengers Bangalore,0,1,0,0,Trent Boult
36,Virat Kohli,Royal Challengers Bangalore,54,37,6,0,Andre Russell
43,Virat Kohli,Royal Challengers Bangalore,31,30,3,0,Ravi Bishnoi
50,Virat Kohli,Royal Challengers Bangalore,55,46,5,0,Mukesh Kumar
54,Virat Kohli,Royal Challengers Bangalore,1,4,0,0,Jason Behrendorff
60,Virat Kohli,Royal Challengers Bangalore,18,19,1,0,KM Asif
65,Virat Kohli,Royal Challengers Bangalore,100,63,12,4,Bhuvneshwar Kumar
70,Virat Kohli,Royal Challengers Bangalore,101,61,13,1,Not Out

In [40]:
# getting all the stats of one specific player i.e Virat Kohli
ipl1.get_group('Virat Kohli').describe()

              Run       Ball      Fours      Sixes
count   14.000000  14.000000  14.000000  14.000000
mean    45.642857  32.642857   4.642857   1.142857
std     34.154867  20.712713   3.973124   1.791310
min      0.000000   1.000000   0.000000   0.000000
25%     18.750000  18.250000   1.500000   0.000000
50%     52.000000  35.500000   4.500000   0.000000
75%     60.500000  46.750000   6.000000   1.000000
max    101.000000  63.000000  13.000000   5.000000

In [41]:
ipl1.get_group('Virat Kohli').median()

C:\Users\Asus\AppData\Local\Temp\ipykernel_12860\2142821655.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  ipl1.get_group('Virat Kohli').median()

Run      52.0
Ball     35.5
Fours     4.5
Sixes     0.0
dtype: float64

In [42]:
#seeing in the maximum fours by vk
ipl1.get_group('Virat Kohli')['Fours'].max()

13

In [43]:
ipl1.count()

                  team  Run  Ball  Fours  Sixes  Wicket taken by
Batsman
Abdul Basith         1    1     1      1      1                1
Abdul Samad          8    8     8      8      8                8
Abhinav Manohar      6    6     6      6      6                6
Abhishek Sharma     11   11    11     11     11               11
Abishek Porel        4    4     4      4      4                4
...                ...  ...   ...    ...    ...              ...
Wayne Parnell        1    1     1      1      1                1
Wriddhiman Saha     14   14    14     14     14               14
Yash Dhull           3    3     3      3      3                3
Yashasvi Jaiswal    14   14    14     14     14               14
Yudhvir Singh        2    2     2      2      2                2

[176 rows x 6 columns]

# Display() function:-

In display() it will gather your output at once place simply we have to pass all the variablbe in display()

In [44]:
# performing the display () to  see virat kohli and abhishek sharma data at one place 

display(ipl1.get_group('Virat Kohli'),ipl1.get_group('Abhishek Sharma'))

,Batsman,team,Run,Ball,Fours,Sixes,Wicket taken by
match_no,,,,,,,
5,Virat Kohli,Royal Challengers Bangalore,82,49,6,5,Not Out
9,Virat Kohli,Royal Challengers Bangalore,21,18,3,0,Sunil Narine
15,Virat Kohli,Royal Challengers Bangalore,61,44,4,4,Amit Mishra
20,Virat Kohli,Royal Challengers Bangalore,50,34,6,1,Lalit Yadav
24,Virat Kohli,Royal Challengers Bangalore,6,4,1,0,Akash Singh
27,Virat Kohli,Royal Challengers Bangalore,59,47,5,1,Harpreet Brar
32,Virat Kohli,Royal Challengers Bangalore,0,1,0,0,Trent Boult
36,Virat Kohli,Royal Challengers Bangalore,54,37,6,0,Andre Russell
43,Virat Kohli,Royal Challengers Bangalore,31,30,3,0,Ravi Bishnoi
50,Virat Kohli,Royal Challengers Bangalore,55,46,5,0,Mukesh Kumar
54,Virat Kohli,Royal Challengers Bangalore,1,4,0,0,Jason Behrendorff
60,Virat Kohli,Royal Challengers Bangalore,18,19,1,0,KM Asif
65,Virat Kohli,Royal Challengers Bangalore,100,63,12,4,Bhuvneshwar Kumar
70,Virat Kohli,Royal Challengers Bangalore,101,61,13,1,Not Out

,Batsman,team,Run,Ball,Fours,Sixes,Wicket taken by
match_no,,,,,,,
4,Abhishek Sharma,Sunrisers Hyderabad,0,3,0,0,Trent Boult
19,Abhishek Sharma,Sunrisers Hyderabad,32,17,3,2,Andre Russell
25,Abhishek Sharma,Sunrisers Hyderabad,1,2,0,0,Piyush Chawla
29,Abhishek Sharma,Sunrisers Hyderabad,34,26,3,1,Ravindra Jadeja
34,Abhishek Sharma,Sunrisers Hyderabad,5,5,0,0,Kuldeep Yadav
40,Abhishek Sharma,Sunrisers Hyderabad,67,36,12,1,Axar Patel
47,Abhishek Sharma,Sunrisers Hyderabad,9,10,1,0,Shardul Thakur
52,Abhishek Sharma,Sunrisers Hyderabad,55,34,5,2,Ravichandran Ashwin
58,Abhishek Sharma,Sunrisers Hyderabad,7,5,1,0,Yudhvir Singh
62,Abhishek Sharma,Sunrisers Hyderabad,4,5,1,0,Yash Dayal
65,Abhishek Sharma,Sunrisers Hyderabad,11,14,2,0,Michael Bracewell

In [45]:
# Seeing the vk and ms dhoni data at one place
display(ipl1.get_group('Virat Kohli'),ipl1.get_group('MS Dhoni'))

,Batsman,team,Run,Ball,Fours,Sixes,Wicket taken by
match_no,,,,,,,
5,Virat Kohli,Royal Challengers Bangalore,82,49,6,5,Not Out
9,Virat Kohli,Royal Challengers Bangalore,21,18,3,0,Sunil Narine
15,Virat Kohli,Royal Challengers Bangalore,61,44,4,4,Amit Mishra
20,Virat Kohli,Royal Challengers Bangalore,50,34,6,1,Lalit Yadav
24,Virat Kohli,Royal Challengers Bangalore,6,4,1,0,Akash Singh
27,Virat Kohli,Royal Challengers Bangalore,59,47,5,1,Harpreet Brar
32,Virat Kohli,Royal Challengers Bangalore,0,1,0,0,Trent Boult
36,Virat Kohli,Royal Challengers Bangalore,54,37,6,0,Andre Russell
43,Virat Kohli,Royal Challengers Bangalore,31,30,3,0,Ravi Bishnoi
50,Virat Kohli,Royal Challengers Bangalore,55,46,5,0,Mukesh Kumar
54,Virat Kohli,Royal Challengers Bangalore,1,4,0,0,Jason Behrendorff
60,Virat Kohli,Royal Challengers Bangalore,18,19,1,0,KM Asif
65,Virat Kohli,Royal Challengers Bangalore,100,63,12,4,Bhuvneshwar Kumar
70,Virat Kohli,Royal Challengers Bangalore,101,61,13,1,Not Out

,Batsman,team,Run,Ball,Fours,Sixes,Wicket taken by
match_no,,,,,,,
1,MS Dhoni,Chennai Super Kings,14,7,1,1,Not Out
6,MS Dhoni,Chennai Super Kings,12,3,0,2,Mark Wood
17,MS Dhoni,Chennai Super Kings,32,17,1,3,Not Out
24,MS Dhoni,Chennai Super Kings,1,1,0,0,Not Out
33,MS Dhoni,Chennai Super Kings,2,3,0,0,Not Out
41,MS Dhoni,Chennai Super Kings,13,4,0,2,Not Out
49,MS Dhoni,Chennai Super Kings,2,3,0,0,Not Out
55,MS Dhoni,Chennai Super Kings,20,9,1,2,Mitchell Marsh
61,MS Dhoni,Chennai Super Kings,2,3,0,0,Not Out
67,MS Dhoni,Chennai Super Kings,5,4,0,0,Not Out

In [46]:
ipl1['Run'].describe().head()

                 count       mean        std  min    25%   50%    75%   max
Batsman
Abdul Basith       1.0   1.000000        NaN  1.0   1.00   1.0   1.00   1.0
Abdul Samad        8.0  21.125000  11.179541  4.0  15.00  21.0  29.00  37.0
Abhinav Manohar    6.0  19.000000  15.569200  2.0   5.75  20.0  26.75  42.0
Abhishek Sharma   11.0  20.454545  23.205015  0.0   4.50   9.0  33.00  67.0
Abishek Porel      4.0   8.250000   8.220908  1.0   4.00   6.0  10.25  20.0

# Aggregate, filter, transform, apply

# Aggregate() 

As we already know the  gorupby aggregate () like  sum(),mean() and  etc.

In groupby aggregate () method allows for even more flexibility. It can take
a string, a function, or a list thereof, and compute all the aggregates at once place.

Groupby aggregate () methed also allows to   pass a dictionary  to perform aggregate ().

In [47]:
# performing the  min,max,mean by passing  through string etc  using aggregate () 

ipl1.aggregate(['min','max','mean']).head()

C:\Users\Asus\AppData\Local\Temp\ipykernel_12860\3606250454.py:3: FutureWarning: ['team', 'Wicket taken by'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  ipl1.aggregate(['min','max','mean']).head()

                Run                Ball                Fours                \
                min max       mean  min max       mean   min max      mean
Batsman
Abdul Basith      1   1   1.000000    1   1   1.000000     0   0  0.000000
Abdul Samad       4  37  21.125000    3  32  16.000000     0   3  1.250000
Abhinav Manohar   2  42  19.000000    3  33  13.833333     0   3  1.000000
Abhishek Sharma   0  67  20.454545    2  36  14.272727     0  12  2.545455
Abishek Porel     1  20   8.250000    3  11   7.750000     0   1  0.250000

                Sixes
                  min max      mean
Batsman
Abdul Basith        0   0  0.000000
Abdul Samad         0   4  1.375000
Abhinav Manohar     0   3  1.166667
Abhishek Sharma     0   2  0.545455
Abishek Porel       0   0  0.000000

In [48]:
# performing the  min,max,mean by passing  through list etc  using aggregate () 
ipl1.aggregate([min,max,sum]).head()

                                team                       \
                                 min                  max
Batsman
Abdul Basith        Rajasthan Royals     Rajasthan Royals
Abdul Samad      Sunrisers Hyderabad  Sunrisers Hyderabad
Abhinav Manohar       Gujarat Titans       Gujarat Titans
Abhishek Sharma  Sunrisers Hyderabad  Sunrisers Hyderabad
Abishek Porel         Delhi Capitals       Delhi Capitals

                                                                   Run      \
                                                               sum min max
Batsman
Abdul Basith                                      Rajasthan Royals   1   1
Abdul Samad      Sunrisers HyderabadSunrisers HyderabadSunriser...   4  37
Abhinav Manohar  Gujarat TitansGujarat TitansGujarat TitansGuja...   2  42
Abhishek Sharma  Sunrisers HyderabadSunrisers HyderabadSunriser...   0  67
Abishek Porel    Delhi CapitalsDelhi CapitalsDelhi CapitalsDelh...   1  20

                     Ball          Fours         Sixes          \
                 sum  min max  sum   min max sum   min max sum
Batsman
Abdul Basith       1    1   1    1     0   0   0     0   0   0
Abdul Samad      169    3  32  128     0   3  10     0   4  11
Abhinav Manohar  114    3  33   83     0   3   6     0   3   7
Abhishek Sharma  225    2  36  157     0  12  28     0   2   6
Abishek Porel     33    3  11   31     0   1   1     0   0   0

                Wicket taken by                       \
                            min                  max
Batsman
Abdul Basith            Not Out              Not Out
Abdul Samad      Mitchell Marsh  Varun Chakaravarthy
Abhinav Manohar      Adam Zampa        Suyash Sharma
Abhishek Sharma   Andre Russell        Yudhvir Singh
Abishek Porel     Harshal Patel     Yuzvendra Chahal


                                                               sum
Batsman
Abdul Basith                                               Not Out
Abdul Samad      Not OutNot OutRun OutMitchell MarshVarun Chaka...
Abhinav Manohar  Suyash SharmaAdam ZampaAmit MishraRiley Meredi...
Abhishek Sharma  Trent BoultAndre RussellPiyush ChawlaRavindra ...
Abishek Porel    Rashid KhanYuzvendra ChahalJason BehrendorffHa...

In [49]:
# performing the  min,max,mean by passing  through string,list etc  using aggregate () 
ipl1.aggregate(['min',max,sum]).head()

                                team                       \
                                 min                  max
Batsman
Abdul Basith        Rajasthan Royals     Rajasthan Royals
Abdul Samad      Sunrisers Hyderabad  Sunrisers Hyderabad
Abhinav Manohar       Gujarat Titans       Gujarat Titans
Abhishek Sharma  Sunrisers Hyderabad  Sunrisers Hyderabad
Abishek Porel         Delhi Capitals       Delhi Capitals

                                                                   Run      \
                                                               sum min max
Batsman
Abdul Basith                                      Rajasthan Royals   1   1
Abdul Samad      Sunrisers HyderabadSunrisers HyderabadSunriser...   4  37
Abhinav Manohar  Gujarat TitansGujarat TitansGujarat TitansGuja...   2  42
Abhishek Sharma  Sunrisers HyderabadSunrisers HyderabadSunriser...   0  67
Abishek Porel    Delhi CapitalsDelhi CapitalsDelhi CapitalsDelh...   1  20

                     Ball          Fours         Sixes          \
                 sum  min max  sum   min max sum   min max sum
Batsman
Abdul Basith       1    1   1    1     0   0   0     0   0   0
Abdul Samad      169    3  32  128     0   3  10     0   4  11
Abhinav Manohar  114    3  33   83     0   3   6     0   3   7
Abhishek Sharma  225    2  36  157     0  12  28     0   2   6
Abishek Porel     33    3  11   31     0   1   1     0   0   0

                Wicket taken by                       \
                            min                  max
Batsman
Abdul Basith            Not Out              Not Out
Abdul Samad      Mitchell Marsh  Varun Chakaravarthy
Abhinav Manohar      Adam Zampa        Suyash Sharma
Abhishek Sharma   Andre Russell        Yudhvir Singh
Abishek Porel     Harshal Patel     Yuzvendra Chahal


                                                               sum
Batsman
Abdul Basith                                               Not Out
Abdul Samad      Not OutNot OutRun OutMitchell MarshVarun Chaka...
Abhinav Manohar  Suyash SharmaAdam ZampaAmit MishraRiley Meredi...
Abhishek Sharma  Trent BoultAndre RussellPiyush ChawlaRavindra ...
Abishek Porel    Rashid KhanYuzvendra ChahalJason BehrendorffHa...

In [50]:
ipl1.aggregate(['min',max,mean]).head()

NameError: name 'mean' is not defined

Here when we pass string list then we can not excute mean as shown above its giving error if we import numpy then it will not give see below it will retun by imporing numpy library.

In [ ]:
# performing the  min,max,mean by passing  through string,list etc  using aggregate ()
import numpy as np
ipl1.aggregate(['min',max,np.mean,np.median]).head()

# Groupby aggregate () methed also allows to   pass a dictionary  to perform aggregate ().

In [ ]:
# passing the dictionary in aggregate () to perform sum artmetic operations
ipl1.aggregate({'Run':'mean',
                'Ball':'sum',
               'Fours':'median',
                'Sixes':'max',}).head()

In [ ]:
# apply aggregate to the single batsman player through list

ipl1.get_group('Virat Kohli').aggregate(['min','max','mean']).head()

In [ ]:
# apply aggregate to the single batsman player through dictionary 

ipl1.get_group('Virat Kohli').aggregate({'Run':'mean',
                                         'Ball':'sum',
                                         'Fours':'median',
                                         'Sixes':'max'}).head()

In [ ]:
# by passing the dictionary 
ipl1.get_group('Virat Kohli').aggregate({'Run':['mean','max',sum,'median','mean']})

# Filtering 

Filtering. A filtering operation allows you to drop data based on the group properties.

Basically it drop the False value and return the True boolean value only.
 
For example suppose  we are performing the addition task of two numbers and want to filter according to its value .
 a=4+5=9 and b=5+3=8 by adding these the value of is a=9 ,b=8
 
if the we filter according to which  is greater then  a or b by applying filter (), then it will only filter which one is greater number simply it will filter a value of a variable  that is 9 and drop the value of b that 8 which is not greater thrn a
thats how filter works

For filtering we make  define function or use lambda function  and pass it in the filter() because the data is in huge

In [51]:
# showing  the dataset
ipl1.head()

,Batsman,team,Run,Ball,Fours,Sixes,Wicket taken by
match_no,,,,,,,
1,Devon Conway,Chennai Super Kings,1,6,0,0,Mohammed Shami
1,Ruturaj Gaikwad,Chennai Super Kings,92,50,4,9,Alzarri Joseph
1,Moeen Ali,Chennai Super Kings,23,17,4,1,Rashid Khan
1,Ben Stokes,Chennai Super Kings,7,6,1,0,Rashid Khan
1,Ambati Rayudu,Chennai Super Kings,12,12,0,1,Joshua Little
...,...,...,...,...,...,...,...
69,Vivrant Sharma,Sunrisers Hyderabad,69,47,9,2,Akash Madhwal
69,Glenn Phillips,Sunrisers Hyderabad,1,4,0,0,Chris Jordan
69,Sanvir Singh,Sunrisers Hyderabad,4,3,1,0,Not Out
70,Michael Bracewell,Royal Challengers Bangalore,26,16,5,0,Mohammed Shami
70,Dasun Shanaka,Gujarat Titans,0,3,0,0,Harshal Patel

In [52]:
# seeing which player has scored  run less then 1 run.
def oye(d):
    return d['Run'].sum()<1

In [53]:
# passing the oye function into the filter ()

w=ipl1.filter(oye)
w

,Batsman,team,Run,Ball,Fours,Sixes,Wicket taken by
match_no,,,,,,,
10,Romario Shepherd,Lucknow Super Giants,0,1,0,0,Adil Rashid
14,Rahul Chahar,Punjab Kings,0,8,0,0,Mayank Markande
15,Avesh Khan,Lucknow Super Giants,0,1,0,0,Not Out
21,Kagiso Rabada,Punjab Kings,0,1,0,0,Not Out
35,Riley Meredith,Mumbai Indians,0,2,0,0,Not Out
38,Rahul Chahar,Punjab Kings,0,1,0,0,Yash Thakur
38,Kagiso Rabada,Punjab Kings,0,1,0,0,Naveen-ul-Haq
47,Harshit Rana,Kolkata Knight Riders,0,1,0,0,Run Out
55,Tushar Deshpande,Chennai Super Kings,0,1,0,0,Not Out
60,KM Asif,Rajasthan Royals,0,2,0,0,Karn Sharma
62,Mohammed Shami,Gujarat Titans,0,1,0,0,Bhuvneshwar Kumar
62,Mohit Sharma,Gujarat Titans,0,1,0,0,Not Out
64,Rahul Chahar,Punjab Kings,0,0,0,0,Not Out

Above data shows run less than 1 

In  groupby filter  we can apply only aggregate to filter the data  and it give True boolean values only that mean whatever value is true after appplying the gaggregate it will show.

In [54]:
# taking the  sum of the  ball by 
def hey(t):
     return t['Ball'].sum()>120

In [55]:
# passing the hey function into the filter ()
d=ipl1.filter(hey)
d

,Batsman,team,Run,Ball,Fours,Sixes,Wicket taken by
match_no,,,,,,,
1,Devon Conway,Chennai Super Kings,1,6,0,0,Mohammed Shami
1,Ruturaj Gaikwad,Chennai Super Kings,92,50,4,9,Alzarri Joseph
1,Shivam Dube,Chennai Super Kings,19,18,0,1,Mohammed Shami
1,Wriddhiman Saha,Gujarat Titans,25,16,2,2,Rajvardhan Hangargekar
1,Shubman Gill,Gujarat Titans,63,36,6,3,Tushar Deshpande
...,...,...,...,...,...,...,...
70,Glenn Maxwell,Royal Challengers Bangalore,11,5,1,1,Rashid Khan
70,Wriddhiman Saha,Gujarat Titans,12,14,2,0,Mohammed Siraj
70,Shubman Gill,Gujarat Titans,104,52,5,8,Not Out
70,Vijay Shankar,Gujarat Titans,53,35,7,2,Vijaykumar Vyshak
70,David Miller,Gujarat Titans,6,7,1,0,Mohammed Siraj

In [56]:
# seeing which batsman has delevered 69 fours in the 2023 ipl season and in which match_no. has score how much fours
def see(g):
    return g['Fours'].sum()==69

In [57]:
dsa=ipl1.filter(see)
dsa

,Batsman,team,Run,Ball,Fours,Sixes,Wicket taken by
match_no,,,,,,,
3,David Warner,Delhi Capitals,56,48,7,0,Avesh Khan
7,David Warner,Delhi Capitals,37,32,7,0,Alzarri Joseph
11,David Warner,Delhi Capitals,65,55,7,0,Yuzvendra Chahal
16,David Warner,Delhi Capitals,51,47,6,0,Jason Behrendorff
20,David Warner,Delhi Capitals,19,13,4,0,Vijaykumar Vyshak
28,David Warner,Delhi Capitals,57,41,11,0,Varun Chakaravarthy
34,David Warner,Delhi Capitals,21,20,2,1,Washington Sundar
40,David Warner,Delhi Capitals,0,2,0,0,Bhuvneshwar Kumar
44,David Warner,Delhi Capitals,2,2,0,0,Run Out
50,David Warner,Delhi Capitals,22,14,3,1,Josh Hazlewood
55,David Warner,Delhi Capitals,0,2,0,0,Deepak Chahar
59,David Warner,Delhi Capitals,54,27,10,1,Harpreet Brar
64,David Warner,Delhi Capitals,46,31,5,2,Sam Curran
67,David Warner,Delhi Capitals,86,58,7,5,Matheesha Pathirana

In [58]:
# seeing the total no.  of fours
dsa['Fours'].sum()

69

In [59]:
# seeing the maximum fours delevere by batsman from the above dsa variable
dsa['Fours'].max()

11

In [60]:
# fetching all the sixes beaten by faf 
sa=ipl1.filter(lambda x: x['Sixes'].sum()>35)
sa

,Batsman,team,Run,Ball,Fours,Sixes,Wicket taken by
match_no,,,,,,,
5,Faf du Plessis,Royal Challengers Bangalore,73,43,5,6,Arshad Khan
9,Faf du Plessis,Royal Challengers Bangalore,23,12,2,2,Varun Chakaravarthy
15,Faf du Plessis,Royal Challengers Bangalore,79,46,5,5,Not Out
20,Faf du Plessis,Royal Challengers Bangalore,22,16,3,1,Mitchell Marsh
24,Faf du Plessis,Royal Challengers Bangalore,62,33,5,4,Moeen Ali
27,Faf du Plessis,Royal Challengers Bangalore,84,56,5,5,Nathan Ellis
32,Faf du Plessis,Royal Challengers Bangalore,62,39,8,2,Run Out
36,Faf du Plessis,Royal Challengers Bangalore,17,7,1,2,Suyash Sharma
43,Faf du Plessis,Royal Challengers Bangalore,44,40,1,1,Amit Mishra
50,Faf du Plessis,Royal Challengers Bangalore,45,32,5,1,Mitchell Marsh
54,Faf du Plessis,Royal Challengers Bangalore,65,41,5,3,Cameron Green
60,Faf du Plessis,Royal Challengers Bangalore,55,44,3,2,KM Asif
65,Faf du Plessis,Royal Challengers Bangalore,71,47,7,2,T Natarajan
70,Faf du Plessis,Royal Challengers Bangalore,28,19,5,0,Noor Ahmad

In [61]:
ipl1['Sixes'].sum().sort_values(ascending=False)

Batsman
Faf du Plessis     36
Shivam Dube        33
Glenn Maxwell      31
Rinku Singh        29
Ruturaj Gaikwad    29
                   ..
Kedar Jadhav        0
Karn Sharma         0
Karan Sharma        0
Kagiso Rabada       0
Yudhvir Singh       0
Name: Sixes, Length: 176, dtype: int64

In [62]:


# seeing both data at once place only 
display(ipl1['Sixes'].sum().sort_values(ascending=False),sa)

Batsman
Faf du Plessis     36
Shivam Dube        33
Glenn Maxwell      31
Rinku Singh        29
Ruturaj Gaikwad    29
                   ..
Kedar Jadhav        0
Karn Sharma         0
Karan Sharma        0
Kagiso Rabada       0
Yudhvir Singh       0
Name: Sixes, Length: 176, dtype: int64

,Batsman,team,Run,Ball,Fours,Sixes,Wicket taken by
match_no,,,,,,,
5,Faf du Plessis,Royal Challengers Bangalore,73,43,5,6,Arshad Khan
9,Faf du Plessis,Royal Challengers Bangalore,23,12,2,2,Varun Chakaravarthy
15,Faf du Plessis,Royal Challengers Bangalore,79,46,5,5,Not Out
20,Faf du Plessis,Royal Challengers Bangalore,22,16,3,1,Mitchell Marsh
24,Faf du Plessis,Royal Challengers Bangalore,62,33,5,4,Moeen Ali
27,Faf du Plessis,Royal Challengers Bangalore,84,56,5,5,Nathan Ellis
32,Faf du Plessis,Royal Challengers Bangalore,62,39,8,2,Run Out
36,Faf du Plessis,Royal Challengers Bangalore,17,7,1,2,Suyash Sharma
43,Faf du Plessis,Royal Challengers Bangalore,44,40,1,1,Amit Mishra
50,Faf du Plessis,Royal Challengers Bangalore,45,32,5,1,Mitchell Marsh
54,Faf du Plessis,Royal Challengers Bangalore,65,41,5,3,Cameron Green
60,Faf du Plessis,Royal Challengers Bangalore,55,44,3,2,KM Asif
65,Faf du Plessis,Royal Challengers Bangalore,71,47,7,2,T Natarajan
70,Faf du Plessis,Royal Challengers Bangalore,28,19,5,0,Noor Ahmad

# Transformation/ Transform()



In transformation  if you want to get a new value for each original row, use tranform()  function .

Basically it put your desired output into your  each original dataset  input  rows  thats how it work like.

As name suggesting it will tranformation can return some transformed version of the full data to recombine and  the output is the same shape as the input.

For example suppose you have small data set of two rows and two columns and have performed sum() aggregation get your desired output  and you want to fill these output  value in the same dataframe without reducing it shape that is rows and columns in the dataset  then you can easily fill by  using these transfrom() methods

In [63]:
# calling the ipl1 dataset 
ipl1.head()

,Batsman,team,Run,Ball,Fours,Sixes,Wicket taken by
match_no,,,,,,,
1,Devon Conway,Chennai Super Kings,1,6,0,0,Mohammed Shami
1,Ruturaj Gaikwad,Chennai Super Kings,92,50,4,9,Alzarri Joseph
1,Moeen Ali,Chennai Super Kings,23,17,4,1,Rashid Khan
1,Ben Stokes,Chennai Super Kings,7,6,1,0,Rashid Khan
1,Ambati Rayudu,Chennai Super Kings,12,12,0,1,Joshua Little
...,...,...,...,...,...,...,...
69,Vivrant Sharma,Sunrisers Hyderabad,69,47,9,2,Akash Madhwal
69,Glenn Phillips,Sunrisers Hyderabad,1,4,0,0,Chris Jordan
69,Sanvir Singh,Sunrisers Hyderabad,4,3,1,0,Not Out
70,Michael Bracewell,Royal Challengers Bangalore,26,16,5,0,Mohammed Shami
70,Dasun Shanaka,Gujarat Titans,0,3,0,0,Harshal Patel

In [64]:
# fetching all records of the one batsman  Devon Conway
ipl1.get_group('Devon Conway')

,Batsman,team,Run,Ball,Fours,Sixes,Wicket taken by
match_no,,,,,,,
1,Devon Conway,Chennai Super Kings,1,6,0,0,Mohammed Shami
6,Devon Conway,Chennai Super Kings,47,29,5,2,Mark Wood
12,Devon Conway,Chennai Super Kings,0,4,0,0,Jason Behrendorff
17,Devon Conway,Chennai Super Kings,50,38,6,0,Yuzvendra Chahal
24,Devon Conway,Chennai Super Kings,83,45,6,6,Harshal Patel
33,Devon Conway,Chennai Super Kings,56,40,4,3,Varun Chakaravarthy
37,Devon Conway,Chennai Super Kings,8,16,1,0,Adam Zampa
41,Devon Conway,Chennai Super Kings,92,52,16,1,Arshdeep Singh
49,Devon Conway,Chennai Super Kings,44,42,4,0,Akash Madhwal
55,Devon Conway,Chennai Super Kings,10,13,1,0,Axar Patel
61,Devon Conway,Chennai Super Kings,30,28,3,0,Shardul Thakur
67,Devon Conway,Chennai Super Kings,87,52,11,3,Anrich Nortje

In [65]:
# fetching all records of the one batsman  Devon Conway and taking its mean()
ipl1.get_group('Devon Conway').mean()

C:\Users\Asus\AppData\Local\Temp\ipykernel_12860\820096279.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  ipl1.get_group('Devon Conway').mean()

Run      42.333333
Ball     30.416667
Fours     4.750000
Sixes     1.250000
dtype: float64

Doing the above task is veru tedious show to see all the mean() in the original data set we can use tranform () instead of doin one by one .

In [66]:
# performing the mean of  using transpose () at ipl1
ipl1.transform(lambda x: x.mean())

C:\Users\Asus\AppData\Local\Temp\ipykernel_12860\1126478881.py:2: FutureWarning: Dropping invalid columns in DataFrameGroupBy.transform is deprecated. In a future version, a TypeError will be raised. Before calling .transform, select only columns which should be valid for the function.
  ipl1.transform(lambda x: x.mean())
C:\Users\Asus\AppData\Local\Temp\ipykernel_12860\1126478881.py:2: FutureWarning: Dropping invalid columns in DataFrameGroupBy.transform is deprecated. In a future version, a TypeError will be raised. Before calling .transform, select only columns which should be valid for the function.
  ipl1.transform(lambda x: x.mean())

                Run       Ball     Fours     Sixes
match_no
1         42.333333  30.416667  4.750000  1.250000
1         41.500000  28.357143  3.428571  2.071429
1         12.777778   9.666667  1.333333  0.555556
1          7.500000   7.000000  1.000000  0.000000
1         12.200000   9.600000  0.800000  0.600000
...             ...        ...       ...       ...
70        48.571429  31.857143  4.785714  1.571429
70        31.888889  19.777778  3.000000  1.555556
70         4.500000   5.000000  0.500000  0.000000
70        21.250000  14.333333  1.500000  1.083333
70         9.333333   5.777778  0.333333  0.777778

[1114 rows x 4 columns]

In the above we can see the mean of the ipl1 dataset 

Basically it adds all the run of player who played matcgh _no 1, and divide this by total inning or numbe rof match  played by the player and given the output as always mean() do.

We are performing the huge amount of data so there might be little confusion while performing the transform method() as learning level.

In [67]:
# performing the max() of  using transpose () at ipl1 
ipl1.transform(lambda x: x.max())

                         team  Run Ball Fours Sixes      Wicket taken by
match_no
1         Chennai Super Kings   92   52    16     6     Yuzvendra Chahal
1         Chennai Super Kings   92   57    12     9  Varun Chakaravarthy
1         Chennai Super Kings   23   17     4     2         Sunil Narine
1         Chennai Super Kings    8    8     1     0          Rashid Khan
1         Chennai Super Kings   27   17     3     2     Yuzvendra Chahal
...                       ...  ...  ...   ...   ...                  ...
70             Gujarat Titans  104   58    13     8     Yuzvendra Chahal
70             Gujarat Titans   63   35     7     5    Vijaykumar Vyshak
70             Gujarat Titans    9    7     1     0              Not Out
70             Gujarat Titans   46   30     4     4          T Natarajan
70             Gujarat Titans   20   14     1     3        Piyush Chawla

[1114 rows x 6 columns]

# The apply() method.

In these method basically we can apply our user define function or lamda and pass it to apply method().

The function should take a DataFrame, and return either a Pandas
object (e.g., DataFrame, Series) or a scalar; the combine operation will be tailored to
the type of output returned.

In [68]:
# calling the ipl1 datasset 
ipl1.head()

,Batsman,team,Run,Ball,Fours,Sixes,Wicket taken by
match_no,,,,,,,
1,Devon Conway,Chennai Super Kings,1,6,0,0,Mohammed Shami
1,Ruturaj Gaikwad,Chennai Super Kings,92,50,4,9,Alzarri Joseph
1,Moeen Ali,Chennai Super Kings,23,17,4,1,Rashid Khan
1,Ben Stokes,Chennai Super Kings,7,6,1,0,Rashid Khan
1,Ambati Rayudu,Chennai Super Kings,12,12,0,1,Joshua Little
...,...,...,...,...,...,...,...
69,Vivrant Sharma,Sunrisers Hyderabad,69,47,9,2,Akash Madhwal
69,Glenn Phillips,Sunrisers Hyderabad,1,4,0,0,Chris Jordan
69,Sanvir Singh,Sunrisers Hyderabad,4,3,1,0,Not Out
70,Michael Bracewell,Royal Challengers Bangalore,26,16,5,0,Mohammed Shami
70,Dasun Shanaka,Gujarat Titans,0,3,0,0,Harshal Patel

In [69]:
# applying() the function to get ball.sum
def he(x):
    x['Ball'].sum()
    return x

In [70]:
ipl1.apply(he)

,Batsman,team,Run,Ball,Fours,Sixes,Wicket taken by
match_no,,,,,,,
1,Ambati Rayudu,Chennai Super Kings,12,12,0,1,Joshua Little
1,Ben Stokes,Chennai Super Kings,7,6,1,0,Rashid Khan
1,Devon Conway,Chennai Super Kings,1,6,0,0,Mohammed Shami
1,Hardik Pandya,Gujarat Titans,8,11,0,0,Ravindra Jadeja
1,MS Dhoni,Chennai Super Kings,14,7,1,1,Not Out
...,...,...,...,...,...,...,...
70,Rahul Tewatia,Gujarat Titans,4,5,0,0,Not Out
70,Shubman Gill,Gujarat Titans,104,52,5,8,Not Out
70,Vijay Shankar,Gujarat Titans,53,35,7,2,Vijaykumar Vyshak
70,Virat Kohli,Royal Challengers Bangalore,101,61,13,1,Not Out
70,Wriddhiman Saha,Gujarat Titans,12,14,2,0,Mohammed Siraj

## conculsion:



when  to use all this function

if we want to get a single value for each group -> use aggregate()

if we want to get a subset of the input rows -> use filter()

if we want to get a new value for each input row -> use transform()